### ISSUE TITLE
Small issue with double quotes

### ISSUE THREAD

**Issue by dieptang** [keitetran/BroadlinkIRTools#1]
Hi, There are small issue with the tool, it's leading the problem to my Hass that the climate was not appeared on the dashboard.

The error "Temperature only accept the number" also throw.
Please make small change on your tool, that when generate the file .json, remove double quotes on "maxTemperature": **"30"** to "maxTemperature": **30** (integer).

Happy coding!

**Comment by keitetran** [comment]
Ok. I wil check and fix it. Thank for report.
