### ISSUE TITLE
Connected but not receiving codes

### ISSUE THREAD

**Issue by chemelli74** [keitetran/BroadlinkIRTools#10]
![Screenshot](https://user-images.githubusercontent.com/57354320/69414876-deb27b00-0d13-11ea-9127-ce391a64be4c.png)
Hi,

I have connected the tool to my HA  version 0.102.0, but it get stuck trying to receive a command.
Please see screenshot attached.

Any idea ?

Thank you,

Simone

**Comment by schteff** [comment]
I have the same issue, using Broadlink Manager I can get the codes, but not using this tool.

**Comment by chemelli74** [comment]
> I have the same issue, using Broadlink Manager I can get the codes, but not using this tool.

You are lucky, I cannot get them even with Broadlink Manager. I have a RM3 mini.
Anything that you can share to help ?
Thank you,

Simone

**Comment by schteff** [comment]
Sorry nothing to share. Does it work with the ihc-app?

**Comment by ssamjh** [comment]
Working with ihc app on Android, however, codes are not being received.

**Comment by schteff** [comment]
@ssamjh try using [Broadlink Manager](https://community.home-assistant.io/t/broadlink-manager-nicer-way-to-learn-and-send-ir-rf-commands/58770) (it worked for me at least). 
Much more copy-pasting than using BroadlinkIRTools but until this is fixed I think it's the easiest temporary solution.

**Comment by chemelli74** [comment]
Fixed after latest protocol upgrade to HA component.

Simone
