### ISSUE TITLE
Home Assistant - API password deprecated

### ISSUE THREAD

**Issue by aheath70** [keitetran/BroadlinkIRTools#3]
Just wondering, with HA deprecating the API password functionality, and with it about to be removed (not sure when, but they keep on promising that it will disappear very soon) do you have a plan for how this might work in the future.

I used this tool to capture my A/C codes for all temperature, modes, etc. It took about 20 minutes. Without this tool it would have taken me hours upon hours, so I would hate to see it disappear - it is truly amazing.

**Comment by keitetran** [comment]
OK i was updated it working with 0.90
