### ISSUE TITLE
 precision step

### ISSUE THREAD

**Issue by quangphuc91** [keitetran/BroadlinkIRTools#4]
Hi, Mr.Anh

Good job man

Can you add a precision step with 2 options?, My AC has  "precision": 0.5 and I can't use your code to make *.json .

Thanks

**Comment by keitetran** [comment]
Thank for report. New field was updated.

**Comment by quangphuc91** [comment]
![image](https://user-images.githubusercontent.com/14102217/55216595-bf6c5800-522f-11e9-8580-b0c0df3bbb66.png)
Thanks for your update, but when i create table, no 0.5 precision field, please review it

**Comment by keitetran** [comment]
New code was updated. Please clean all browser cache befor use.

**Comment by quangphuc91** [comment]
thank you very much, It’s helpfull
