### ISSUE TITLE
Broadlink Service

### ISSUE THREAD

**Issue by Shu-S** [keitetran/BroadlinkIRTools#7]
Home assistant broadlink service has changed to broadlink.learn can you please update the code. Thanks

**Comment by unclehook** [comment]
I have made a workaround.
Source: https://github.com/unclehook/BroadlinkIRTools
Dist URL: https://unclehook.github.io/BroadlinkIRTools/#/

Test and report, please.

@keitetran feel free to integrate with your source.

**Comment by keitetran** [comment]
Can u create a pull request. ?

**Comment by sasukebinbin** [comment]
What means of pull request? I also have the same issue. Original learn command is not working any more. Now service name is broadlink.learn with "host":"IP address" in service data. But not sure how to format it. 
<img width="692" alt="屏幕快照 2019-05-23 下午11 36 09" src="https://user-images.githubusercontent.com/36916438/58266105-9b527080-7db3-11e9-9fb4-a4d3a19d0339.png">

**Comment by sasukebinbin** [comment]
Please help thanks a lot

**Comment by unclehook** [comment]
@keitetran Pull request created.

**Comment by unclehook** [comment]
@sasukebinbin: The pull request was form me an my fork with the workaround. If you cannot wait for the "merge" of keitetran in his repository, you can go here https://github.com/unclehook/BroadlinkIRTools and follow the instruction.  For the future if you not understand what is talking about, don't think someone is talking with you.

**Comment by keitetran** [comment]
Sorry bro, i was updated my HASS to lastest version. Wait me fix that.

**Comment by keitetran** [comment]
New code was updated. THank you for report.
